language: node_js
node_js:
  - "6"
notifications:
  email: false

cache:
  directories:
    - node_modules
    
before_script:
  - npm install --save-dev nyc
  
before_build:
  - ./cc-test-reporter before-build

script:
  - npm run test

after_build:
  - ./cc-test-reporter after-build --exit-code $EXIT_CODE
