language: node_js
node_js:
  - "6"
notifications:
  email: false

cache:
  directories:
    - node_modules
    
before_script:
  - npm install --save-dev nyc

script:
  - npm run test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
